apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-template
spec:
  templates:
  - name: build
    container:
      image: busybox
      command: [sh, -c]
      args:
        - echo "Build template"
