apiVersion: v2
name: my-wordpress
description: Wordpress wrapper chart
type: application
version: 0.1.0

dependencies:
  - name: wordpress
    version: 25.0.0
    repository: https://charts.bitnami.com/bitnami
